### ISSUE TITLE
USER STORY:  View film dates and choose a film

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/cinerama-cinema#10]
Epic: #6

As a **Site User** I can **can choose a film to watch, depending on date, by adding a number of tickets** so that **I can watch a film when I´m free  according to my calendar**.

**Tasks:**
- [x] Create booking model and snack model.
- [x] Create booking HTML template extending base template, to display film showtimes to user and form to make booking. Add CSS styling.
- [x] Create filter on date, to show available films. 
- [x] Make the booking page responsive.

**Acceptance Criteria:**
- The user needs to have a clear overview of films available to watch on a specific day.
- Selecting a film needs to be easy and require as few clicks as possible.
