### ISSUE TITLE
USER STORY:  View snacks meny and choose snacks

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/cinerama-cinema#13]
Epic: #6 

As a **Site User** I can **view the snacks meny and choose snacks** so that **I can eat and drink during a film**.

**Tasks:**
- [x] Include HTML code in booking template form, to show snacks that can be booked (optional). 
- [x] Add CSS styling.
- [x] Make the booking page responsive. 

**Acceptance Criteria:**
- If the user wants to, it needs to be able to eat and drink during a film.
- There needs to be several different snacks to choose from.
