### ISSUE TITLE
USER STORY:  Login

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/cinerama-cinema#18]
Epic: #1 

As a **registered Site User** I can **log in with my username and password** so that **the system can authenticate me**.

**Tasks:**
- [x] Customize allauth HTML signin template and add custom CSS code for signup/registration form.
- [x] Make the registration page responsive.
- [x] Add success message for successful signin.

**Acceptance Criteria:**
- The user needs to get at clear login form, that enables fast and easy login.
- Signin form must be validated and look good on all standard devices.
- All invald user form input to signin form must be alerted to the user. The user should also be alerted when login/logout was successful. 
- A user can only be signed in if it has registered an account and enters valid username or password in signin form. The signin form must be validated.
