### ISSUE TITLE
USER STORY:  Account registration

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/cinerama-cinema#2]
Epic: #1

As a **Site User** I can **register an account** so that **I can book tickets to see a movie and eat**.

**Tasks:**
- [x] Create customized user model, extending allauth user model with first and last name.
- [x] Customize allauth HTML signup template and add custom CSS code for signup/registration form. 
- [x] Make the registration page responsive.
- [x] Add success message for successful registration.

**Acceptance Criteria:**
- Registration requires at least name and email to be entered, so that the customer can be contacted if necessary. Password is also required.
- Registration form must be validated and look good on all standard devices.
- User must be alerted when registration has been successful and when field input is invalid.
