### ISSUE TITLE
USER STORY:  Edit and cancel booking

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/cinerama-cinema#3]
Epic: #1  

As a **Site User** I can **edit or cancel a ticket booking on my profile page** so that **I can manage my bookings**.

**Tasks:**
- [x] Create edit and cancel templates extending base template. They can only be reached from the user booking overview page (that only authentivcated users can see).
- [x] Add edit/canceling functionality for each booking.
- [x] Add success and error message for valid and invalid editing or canceling. 

**Acceptance Criteria:**
- An authenticated user must be able to edit or cancel any of their bookings.
- Editing needs to be done at a separate page. Canceling too.
