### ISSUE TITLE
USER STORY:  View list of films

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/cinerama-cinema#7]
Epic: #4 

As a **Site User** I can **view a list of films** so that **I can choose which one I want to watch**.

**Tasks:**
- [x] Develop HTML template and CSS code for base.html home page with navbar, logo and footer.
- [x] Develop HTML template, CSS code, Film model and Genre model to show each film as a card, with the film title, genre, runtime and a nice image. 
- [x] Implement Materialize card reveal functionality on each card, to show more information about the film plot and a link to the film trailer. 
- [x] Add responsivness.

**Acceptance Criteria:**
- When I as a site user go to the home page I should be able to view a list of all films available to watch at the cinema.
- If I as a site user click on a film, I need to be able to get more information about the film plot, so that I can choose a film based on what I like to watch. 
- When I as a site user visit the site, I should easily be able to find the opening hours and how to contact the cinema.
